os:
  - linux
  - osx
language: node_js
node_js:
  - '10'
  - '12'
  - '14'

before_install:
  - npm install -g nyc mocha codeclimate-test-reporter

after_success:
  - nyc --reporter=lcov npm test
  - nyc report --reporter=lcov
