name: Feature request
description: Suggest an idea for this project
labels: [ Enhancement, Verification ]
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for feature requests only!
        If you have a problem or if you just want to ask a question, please use one of the other templates.
  - type: textarea
    validations:
      required: true
    attributes:
      label: The feature request
      description: >-
        Please provide a clear and concise description of what you want to happen.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: dropdown
    id: device
    validations:
      required: false
    attributes:
      label: Which model do you own?
      options:
        - Deebot OZMO 920
        - Deebot OZMO 950
        - Deebot U2 series
        - Deebot N8 series
        - Deebot N9 series
        - Deebot N10 series
        - Deebot T8 series
        - Deebot T9 series
        - Deebot T10 series
        - Deebot T20 series
        - Deebot X1 series
        - Deebot X2 series
        - Other model (Please fill out the fields at the bottom of the form)
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
  - type: input
    id: otherDevice
    validations:
      required: false
    attributes:
      label: Which "other" models are you using?
      placeholder: Deebot [OZMO] xxx
      description: >
        Only needed if the model is not listed above ("With which model does the problem occur?") or if you use more than one model with this adapter